services:
  - name: frontend
    env: node
    buildCommand: npm run build
    startCommand: npm run dev
    buildDir: frontend
    

  - name: backend
    env: node
    buildCommand: npm run build
    startCommand: node server.js
    buildDir: backend
   
